create table if not exists public.vendr_stock_depletion (
  world_key text not null default 'public-2045',
  entity_id text not null,
  item_id text not null,
  stock_cycle bigint not null,
  baseline_quantity integer not null check (baseline_quantity >= 0),
  quantity_depleted integer not null default 0 check (quantity_depleted >= 0),
  updated_at timestamptz not null default now(),
  primary key (world_key, entity_id, item_id, stock_cycle)
);

create index if not exists vendr_stock_depletion_entity_cycle_idx
  on public.vendr_stock_depletion (world_key, entity_id, stock_cycle);

alter table public.vendr_stock_depletion enable row level security;

create table if not exists public.vendr_stock_events (
  id bigint generated by default as identity primary key,
  event_uuid uuid not null default gen_random_uuid() unique,
  world_key text not null default 'public-2045',
  entity_id text not null,
  item_id text,
  stock_cycle bigint,
  event_type text not null check (event_type in ('purchase','adjustment','restock')),
  quantity_delta integer,
  unit_price numeric,
  actor_key text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists vendr_stock_events_entity_idx
  on public.vendr_stock_events (world_key, entity_id, occurred_at desc);

alter table public.vendr_stock_events enable row level security;

create or replace function public.vendr_apply_purchase(
  p_world_key text,
  p_entity_id text,
  p_item_id text,
  p_stock_cycle bigint,
  p_quantity integer,
  p_baseline_quantity integer,
  p_unit_price numeric default null,
  p_actor_key text default null,
  p_metadata jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.vendr_stock_depletion%rowtype;
  v_remaining integer;
begin
  if p_quantity is null or p_quantity < 1 then
    raise exception 'quantity must be at least 1' using errcode='22023';
  end if;
  if p_baseline_quantity is null or p_baseline_quantity < 1 then
    raise exception 'baseline quantity must be at least 1' using errcode='22023';
  end if;
  if p_quantity > p_baseline_quantity then
    raise exception 'insufficient stock' using errcode='P0001';
  end if;

  insert into public.vendr_stock_depletion(
    world_key, entity_id, item_id, stock_cycle,
    baseline_quantity, quantity_depleted, updated_at
  )
  values(
    coalesce(nullif(p_world_key,''),'public-2045'),
    p_entity_id, p_item_id, p_stock_cycle,
    p_baseline_quantity, p_quantity, now()
  )
  on conflict (world_key, entity_id, item_id, stock_cycle)
  do update set
    quantity_depleted = public.vendr_stock_depletion.quantity_depleted + excluded.quantity_depleted,
    updated_at = now()
  where public.vendr_stock_depletion.quantity_depleted + excluded.quantity_depleted
        <= public.vendr_stock_depletion.baseline_quantity
  returning * into v_row;

  if not found then
    raise exception 'insufficient stock' using errcode='P0001';
  end if;

  v_remaining := greatest(0, v_row.baseline_quantity - v_row.quantity_depleted);

  insert into public.vendr_stock_events(
    world_key, entity_id, item_id, stock_cycle, event_type,
    quantity_delta, unit_price, actor_key, metadata
  ) values (
    v_row.world_key, p_entity_id, p_item_id, p_stock_cycle, 'purchase',
    -p_quantity, p_unit_price, p_actor_key, coalesce(p_metadata,'{}'::jsonb)
  );

  return jsonb_build_object(
    'ok', true,
    'world_key', v_row.world_key,
    'entity_id', p_entity_id,
    'item_id', p_item_id,
    'stock_cycle', p_stock_cycle,
    'quantity_purchased', p_quantity,
    'quantity_depleted', v_row.quantity_depleted,
    'remaining', v_remaining
  );
end;
$$;

revoke all on function public.vendr_apply_purchase(text,text,text,bigint,integer,integer,numeric,text,jsonb) from public;
revoke all on function public.vendr_apply_purchase(text,text,text,bigint,integer,integer,numeric,text,jsonb) from anon;
revoke all on function public.vendr_apply_purchase(text,text,text,bigint,integer,integer,numeric,text,jsonb) from authenticated;
grant execute on function public.vendr_apply_purchase(text,text,text,bigint,integer,integer,numeric,text,jsonb) to service_role;
